# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guide.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'guide.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bguide.proto\x12\x05guide\"\x16\n\x07UserMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x17\n\x08GuideMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t2>\n\x05Guide\x12\x35\n\x10ThinkResponseMsg\x12\x0e.guide.UserMsg\x1a\x0f.guide.GuideMsg\"\x00\x42H\n2dev.yukky-sandbox.yukky-sandbox-guide-server.guideB\nGuideProtoP\x01\xa2\x02\x03GIDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guide_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2dev.yukky-sandbox.yukky-sandbox-guide-server.guideB\nGuideProtoP\001\242\002\003GID'
  _globals['_USERMSG']._serialized_start=22
  _globals['_USERMSG']._serialized_end=44
  _globals['_GUIDEMSG']._serialized_start=46
  _globals['_GUIDEMSG']._serialized_end=69
  _globals['_GUIDE']._serialized_start=71
  _globals['_GUIDE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
